/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The CreateConstraintRequest model module.
* @module model/CreateConstraintRequest
* @version 1.0.0
*/
export default class CreateConstraintRequest {
    /**
    * Constructs a new <code>CreateConstraintRequest</code>.
    * @alias module:model/CreateConstraintRequest
    * @class
    * @param property {String} 
    * @param operator {String} 
    * @param value {String} 
    */

    constructor(property, operator, value) {
        

        
        

        this['property'] = property;this['operator'] = operator;this['value'] = value;

        
    }

    /**
    * Constructs a <code>CreateConstraintRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreateConstraintRequest} obj Optional instance to populate.
    * @return {module:model/CreateConstraintRequest} The populated <code>CreateConstraintRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateConstraintRequest();

            
            
            

            if (data.hasOwnProperty('property')) {
                obj['property'] = ApiClient.convertToType(data['property'], 'String');
            }
            if (data.hasOwnProperty('operator')) {
                obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} property
    */
    property = undefined;
    /**
    * @member {String} operator
    */
    operator = undefined;
    /**
    * @member {String} value
    */
    value = undefined;








}


