/*
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 
 *
 * OpenAPI spec version: 1.1.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Jsflagr) {
      root.Jsflagr = {};
    }
    root.Jsflagr.CreateTagRequest = factory(root.Jsflagr.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The CreateTagRequest model module.
   * @module model/CreateTagRequest
   * @version 1.1.10
   */

  /**
   * Constructs a new <code>CreateTagRequest</code>.
   * @alias module:model/CreateTagRequest
   * @class
   * @param value {String} 
   */
  var exports = function(value) {
    this.value = value;
  };

  /**
   * Constructs a <code>CreateTagRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateTagRequest} obj Optional instance to populate.
   * @return {module:model/CreateTagRequest} The populated <code>CreateTagRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} value
   */
  exports.prototype.value = undefined;

  return exports;

}));
