/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Distribution model module.
* @module model/Distribution
* @version 1.0.0
*/
export default class Distribution {
    /**
    * Constructs a new <code>Distribution</code>.
    * @alias module:model/Distribution
    * @class
    * @param percent {Number} 
    * @param variantKey {String} 
    * @param variantID {Number} 
    */

    constructor(percent, variantKey, variantID) {
        

        
        

        this['percent'] = percent;this['variantKey'] = variantKey;this['variantID'] = variantID;

        
    }

    /**
    * Constructs a <code>Distribution</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Distribution} obj Optional instance to populate.
    * @return {module:model/Distribution} The populated <code>Distribution</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Distribution();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('percent')) {
                obj['percent'] = ApiClient.convertToType(data['percent'], 'Number');
            }
            if (data.hasOwnProperty('bitmap')) {
                obj['bitmap'] = ApiClient.convertToType(data['bitmap'], 'String');
            }
            if (data.hasOwnProperty('variantKey')) {
                obj['variantKey'] = ApiClient.convertToType(data['variantKey'], 'String');
            }
            if (data.hasOwnProperty('variantID')) {
                obj['variantID'] = ApiClient.convertToType(data['variantID'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {Number} percent
    */
    percent = undefined;
    /**
    * @member {String} bitmap
    */
    bitmap = undefined;
    /**
    * @member {String} variantKey
    */
    variantKey = undefined;
    /**
    * @member {Number} variantID
    */
    variantID = undefined;








}


