/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import EvalResult from './EvalResult';





/**
* The EvaluationBatchResponse model module.
* @module model/EvaluationBatchResponse
* @version 1.0.0
*/
export default class EvaluationBatchResponse {
    /**
    * Constructs a new <code>EvaluationBatchResponse</code>.
    * @alias module:model/EvaluationBatchResponse
    * @class
    * @param evaluationResults {Array.<module:model/EvalResult>} 
    */

    constructor(evaluationResults) {
        

        
        

        this['evaluationResults'] = evaluationResults;

        
    }

    /**
    * Constructs a <code>EvaluationBatchResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EvaluationBatchResponse} obj Optional instance to populate.
    * @return {module:model/EvaluationBatchResponse} The populated <code>EvaluationBatchResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EvaluationBatchResponse();

            
            
            

            if (data.hasOwnProperty('evaluationResults')) {
                obj['evaluationResults'] = ApiClient.convertToType(data['evaluationResults'], [EvalResult]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/EvalResult>} evaluationResults
    */
    evaluationResults = undefined;








}


