/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import SegmentDebugLog from './SegmentDebugLog';





/**
* The EvalDebugLog model module.
* @module model/EvalDebugLog
* @version 1.0.0
*/
export default class EvalDebugLog {
    /**
    * Constructs a new <code>EvalDebugLog</code>.
    * @alias module:model/EvalDebugLog
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>EvalDebugLog</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EvalDebugLog} obj Optional instance to populate.
    * @return {module:model/EvalDebugLog} The populated <code>EvalDebugLog</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EvalDebugLog();

            
            
            

            if (data.hasOwnProperty('segmentDebugLogs')) {
                obj['segmentDebugLogs'] = ApiClient.convertToType(data['segmentDebugLogs'], [SegmentDebugLog]);
            }
            if (data.hasOwnProperty('msg')) {
                obj['msg'] = ApiClient.convertToType(data['msg'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/SegmentDebugLog>} segmentDebugLogs
    */
    segmentDebugLogs = undefined;
    /**
    * @member {String} msg
    */
    msg = undefined;








}


