/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Segment from './Segment';
import Variant from './Variant';





/**
* The Flag model module.
* @module model/Flag
* @version 1.0.0
*/
export default class Flag {
    /**
    * Constructs a new <code>Flag</code>.
    * @alias module:model/Flag
    * @class
    * @param description {String} 
    * @param enabled {Boolean} 
    * @param dataRecordsEnabled {Boolean} enabled data records will get data logging in the metrics pipeline, for example, kafka.
    */

    constructor(description, enabled, dataRecordsEnabled) {
        

        
        

        this['description'] = description;this['enabled'] = enabled;this['dataRecordsEnabled'] = dataRecordsEnabled;

        
    }

    /**
    * Constructs a <code>Flag</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Flag} obj Optional instance to populate.
    * @return {module:model/Flag} The populated <code>Flag</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Flag();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('segments')) {
                obj['segments'] = ApiClient.convertToType(data['segments'], [Segment]);
            }
            if (data.hasOwnProperty('variants')) {
                obj['variants'] = ApiClient.convertToType(data['variants'], [Variant]);
            }
            if (data.hasOwnProperty('dataRecordsEnabled')) {
                obj['dataRecordsEnabled'] = ApiClient.convertToType(data['dataRecordsEnabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    id = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Boolean} enabled
    */
    enabled = undefined;
    /**
    * @member {Array.<module:model/Segment>} segments
    */
    segments = undefined;
    /**
    * @member {Array.<module:model/Variant>} variants
    */
    variants = undefined;
    /**
    * enabled data records will get data logging in the metrics pipeline, for example, kafka.
    * @member {Boolean} dataRecordsEnabled
    */
    dataRecordsEnabled = undefined;








}


