/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PutFlagRequest model module.
* @module model/PutFlagRequest
* @version 1.0.0
*/
export default class PutFlagRequest {
    /**
    * Constructs a new <code>PutFlagRequest</code>.
    * @alias module:model/PutFlagRequest
    * @class
    * @param description {String} 
    */

    constructor(description) {
        

        
        

        this['description'] = description;

        
    }

    /**
    * Constructs a <code>PutFlagRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PutFlagRequest} obj Optional instance to populate.
    * @return {module:model/PutFlagRequest} The populated <code>PutFlagRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PutFlagRequest();

            
            
            

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('dataRecordsEnabled')) {
                obj['dataRecordsEnabled'] = ApiClient.convertToType(data['dataRecordsEnabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * enabled data records will get data logging in the metrics pipeline, for example, kafka.
    * @member {Boolean} dataRecordsEnabled
    */
    dataRecordsEnabled = undefined;








}


