/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.8
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Flagr) {
      root.Flagr = {};
    }
    root.Flagr.PutFlagRequest = factory(root.Flagr.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PutFlagRequest model module.
   * @module model/PutFlagRequest
   * @version 1.0.8
   */

  /**
   * Constructs a new <code>PutFlagRequest</code>.
   * @alias module:model/PutFlagRequest
   * @class
   * @param description {String} 
   */
  var exports = function(description) {
    var _this = this;

    _this['description'] = description;

  };

  /**
   * Constructs a <code>PutFlagRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PutFlagRequest} obj Optional instance to populate.
   * @return {module:model/PutFlagRequest} The populated <code>PutFlagRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('dataRecordsEnabled')) {
        obj['dataRecordsEnabled'] = ApiClient.convertToType(data['dataRecordsEnabled'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * enabled data records will get data logging in the metrics pipeline, for example, kafka.
   * @member {Boolean} dataRecordsEnabled
   */
  exports.prototype['dataRecordsEnabled'] = undefined;



  return exports;
}));


