/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PutSegmentRequest model module.
* @module model/PutSegmentRequest
* @version 1.0.0
*/
export default class PutSegmentRequest {
    /**
    * Constructs a new <code>PutSegmentRequest</code>.
    * @alias module:model/PutSegmentRequest
    * @class
    * @param description {String} 
    * @param rolloutPercent {Number} 
    */

    constructor(description, rolloutPercent) {
        

        
        

        this['description'] = description;this['rolloutPercent'] = rolloutPercent;

        
    }

    /**
    * Constructs a <code>PutSegmentRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PutSegmentRequest} obj Optional instance to populate.
    * @return {module:model/PutSegmentRequest} The populated <code>PutSegmentRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PutSegmentRequest();

            
            
            

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('rolloutPercent')) {
                obj['rolloutPercent'] = ApiClient.convertToType(data['rolloutPercent'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Number} rolloutPercent
    */
    rolloutPercent = undefined;








}


