/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PutSegmentReorderRequest model module.
* @module model/PutSegmentReorderRequest
* @version 1.0.0
*/
export default class PutSegmentReorderRequest {
    /**
    * Constructs a new <code>PutSegmentReorderRequest</code>.
    * @alias module:model/PutSegmentReorderRequest
    * @class
    * @param segmentIDs {Array.<Number>} 
    */

    constructor(segmentIDs) {
        

        
        

        this['segmentIDs'] = segmentIDs;

        
    }

    /**
    * Constructs a <code>PutSegmentReorderRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PutSegmentReorderRequest} obj Optional instance to populate.
    * @return {module:model/PutSegmentReorderRequest} The populated <code>PutSegmentReorderRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PutSegmentReorderRequest();

            
            
            

            if (data.hasOwnProperty('segmentIDs')) {
                obj['segmentIDs'] = ApiClient.convertToType(data['segmentIDs'], ['Number']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<Number>} segmentIDs
    */
    segmentIDs = undefined;








}


