/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 
 *
 * OpenAPI spec version: 1.0.13
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Constraint', 'model/Distribution'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Constraint'), require('./Distribution'));
  } else {
    // Browser globals (root is window)
    if (!root.Jsflagr) {
      root.Jsflagr = {};
    }
    root.Jsflagr.Segment = factory(root.Jsflagr.ApiClient, root.Jsflagr.Constraint, root.Jsflagr.Distribution);
  }
}(this, function(ApiClient, Constraint, Distribution) {
  'use strict';




  /**
   * The Segment model module.
   * @module model/Segment
   * @version 1.0.13
   */

  /**
   * Constructs a new <code>Segment</code>.
   * @alias module:model/Segment
   * @class
   * @param description {String} 
   * @param rank {Number} 
   * @param rolloutPercent {Number} 
   */
  var exports = function(description, rank, rolloutPercent) {
    var _this = this;


    _this['description'] = description;


    _this['rank'] = rank;
    _this['rolloutPercent'] = rolloutPercent;
  };

  /**
   * Constructs a <code>Segment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Segment} obj Optional instance to populate.
   * @return {module:model/Segment} The populated <code>Segment</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('constraints')) {
        obj['constraints'] = ApiClient.convertToType(data['constraints'], [Constraint]);
      }
      if (data.hasOwnProperty('distributions')) {
        obj['distributions'] = ApiClient.convertToType(data['distributions'], [Distribution]);
      }
      if (data.hasOwnProperty('rank')) {
        obj['rank'] = ApiClient.convertToType(data['rank'], 'Number');
      }
      if (data.hasOwnProperty('rolloutPercent')) {
        obj['rolloutPercent'] = ApiClient.convertToType(data['rolloutPercent'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Array.<module:model/Constraint>} constraints
   */
  exports.prototype['constraints'] = undefined;
  /**
   * @member {Array.<module:model/Distribution>} distributions
   */
  exports.prototype['distributions'] = undefined;
  /**
   * @member {Number} rank
   */
  exports.prototype['rank'] = undefined;
  /**
   * @member {Number} rolloutPercent
   */
  exports.prototype['rolloutPercent'] = undefined;



  return exports;
}));


