/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The SetFlagEnabledRequest model module.
* @module model/SetFlagEnabledRequest
* @version 1.0.0
*/
export default class SetFlagEnabledRequest {
    /**
    * Constructs a new <code>SetFlagEnabledRequest</code>.
    * @alias module:model/SetFlagEnabledRequest
    * @class
    * @param enabled {Boolean} 
    */

    constructor(enabled) {
        

        
        

        this['enabled'] = enabled;

        
    }

    /**
    * Constructs a <code>SetFlagEnabledRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SetFlagEnabledRequest} obj Optional instance to populate.
    * @return {module:model/SetFlagEnabledRequest} The populated <code>SetFlagEnabledRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetFlagEnabledRequest();

            
            
            

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} enabled
    */
    enabled = undefined;








}


