/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Distribution', 'model/Error', 'model/PutDistributionsRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Distribution'), require('../model/Error'), require('../model/PutDistributionsRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.Jsflagr) {
      root.Jsflagr = {};
    }
    root.Jsflagr.DistributionApi = factory(root.Jsflagr.ApiClient, root.Jsflagr.Distribution, root.Jsflagr.Error, root.Jsflagr.PutDistributionsRequest);
  }
}(this, function(ApiClient, Distribution, Error, PutDistributionsRequest) {
  'use strict';

  /**
   * Distribution service.
   * @module api/DistributionApi
   * @version 1.1.0
   */

  /**
   * Constructs a new DistributionApi. 
   * @alias module:api/DistributionApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the findDistributions operation.
     * @callback module:api/DistributionApi~findDistributionsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Distribution>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} flagID numeric ID of the flag
     * @param {Number} segmentID numeric ID of the segment
     * @param {module:api/DistributionApi~findDistributionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Distribution>}
     */
    this.findDistributions = function(flagID, segmentID, callback) {
      var postBody = null;

      // verify the required parameter 'flagID' is set
      if (flagID === undefined || flagID === null) {
        throw new Error("Missing the required parameter 'flagID' when calling findDistributions");
      }

      // verify the required parameter 'segmentID' is set
      if (segmentID === undefined || segmentID === null) {
        throw new Error("Missing the required parameter 'segmentID' when calling findDistributions");
      }


      var pathParams = {
        'flagID': flagID,
        'segmentID': segmentID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Distribution];

      return this.apiClient.callApi(
        '/flags/{flagID}/segments/{segmentID}/distributions', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the putDistributions operation.
     * @callback module:api/DistributionApi~putDistributionsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Distribution>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * replace the distribution with the new setting
     * @param {Number} flagID numeric ID of the flag
     * @param {Number} segmentID numeric ID of the segment
     * @param {module:model/PutDistributionsRequest} body array of distributions
     * @param {module:api/DistributionApi~putDistributionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Distribution>}
     */
    this.putDistributions = function(flagID, segmentID, body, callback) {
      var postBody = body;

      // verify the required parameter 'flagID' is set
      if (flagID === undefined || flagID === null) {
        throw new Error("Missing the required parameter 'flagID' when calling putDistributions");
      }

      // verify the required parameter 'segmentID' is set
      if (segmentID === undefined || segmentID === null) {
        throw new Error("Missing the required parameter 'segmentID' when calling putDistributions");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling putDistributions");
      }


      var pathParams = {
        'flagID': flagID,
        'segmentID': segmentID
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Distribution];

      return this.apiClient.callApi(
        '/flags/{flagID}/segments/{segmentID}/distributions', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
