/*
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 
 *
 * OpenAPI spec version: 1.1.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Jsflagr);
  }
}(this, function(expect, Jsflagr) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Distribution', function() {
      beforeEach(function() {
        instance = new Jsflagr.Distribution();
      });

      it('should create an instance of Distribution', function() {
        // TODO: update the code to test Distribution
        expect(instance).to.be.a(Jsflagr.Distribution);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property percent (base name: "percent")', function() {
        // TODO: update the code to test the property percent
        expect(instance).to.have.property('percent');
        // expect(instance.percent).to.be(expectedValueLiteral);
      });

      it('should have the property variantKey (base name: "variantKey")', function() {
        // TODO: update the code to test the property variantKey
        expect(instance).to.have.property('variantKey');
        // expect(instance.variantKey).to.be(expectedValueLiteral);
      });

      it('should have the property variantID (base name: "variantID")', function() {
        // TODO: update the code to test the property variantID
        expect(instance).to.have.property('variantID');
        // expect(instance.variantID).to.be(expectedValueLiteral);
      });

    });
  });

}));
