/*
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 
 *
 * OpenAPI spec version: 1.1.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Jsflagr);
  }
}(this, function(expect, Jsflagr) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('EvalContext', function() {
      beforeEach(function() {
        instance = new Jsflagr.EvalContext();
      });

      it('should create an instance of EvalContext', function() {
        // TODO: update the code to test EvalContext
        expect(instance).to.be.a(Jsflagr.EvalContext);
      });

      it('should have the property entityID (base name: "entityID")', function() {
        // TODO: update the code to test the property entityID
        expect(instance).to.have.property('entityID');
        // expect(instance.entityID).to.be(expectedValueLiteral);
      });

      it('should have the property entityType (base name: "entityType")', function() {
        // TODO: update the code to test the property entityType
        expect(instance).to.have.property('entityType');
        // expect(instance.entityType).to.be(expectedValueLiteral);
      });

      it('should have the property entityContext (base name: "entityContext")', function() {
        // TODO: update the code to test the property entityContext
        expect(instance).to.have.property('entityContext');
        // expect(instance.entityContext).to.be(expectedValueLiteral);
      });

      it('should have the property enableDebug (base name: "enableDebug")', function() {
        // TODO: update the code to test the property enableDebug
        expect(instance).to.have.property('enableDebug');
        // expect(instance.enableDebug).to.be(expectedValueLiteral);
      });

      it('should have the property flagID (base name: "flagID")', function() {
        // TODO: update the code to test the property flagID
        expect(instance).to.have.property('flagID');
        // expect(instance.flagID).to.be(expectedValueLiteral);
      });

      it('should have the property flagKey (base name: "flagKey")', function() {
        // TODO: update the code to test the property flagKey
        expect(instance).to.have.property('flagKey');
        // expect(instance.flagKey).to.be(expectedValueLiteral);
      });

      it('should have the property flagTags (base name: "flagTags")', function() {
        // TODO: update the code to test the property flagTags
        expect(instance).to.have.property('flagTags');
        // expect(instance.flagTags).to.be(expectedValueLiteral);
      });

    });
  });

}));
