/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Jsflagr);
  }
}(this, function(expect, Jsflagr) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Jsflagr.EvalContext();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EvalContext', function() {
    it('should create an instance of EvalContext', function() {
      // uncomment below and update the code to test EvalContext
      //var instance = new Jsflagr.EvalContext();
      //expect(instance).to.be.a(Jsflagr.EvalContext);
    });

    it('should have the property entityID (base name: "entityID")', function() {
      // uncomment below and update the code to test the property entityID
      //var instance = new Jsflagr.EvalContext();
      //expect(instance).to.be();
    });

    it('should have the property entityType (base name: "entityType")', function() {
      // uncomment below and update the code to test the property entityType
      //var instance = new Jsflagr.EvalContext();
      //expect(instance).to.be();
    });

    it('should have the property entityContext (base name: "entityContext")', function() {
      // uncomment below and update the code to test the property entityContext
      //var instance = new Jsflagr.EvalContext();
      //expect(instance).to.be();
    });

    it('should have the property enableDebug (base name: "enableDebug")', function() {
      // uncomment below and update the code to test the property enableDebug
      //var instance = new Jsflagr.EvalContext();
      //expect(instance).to.be();
    });

    it('should have the property flagID (base name: "flagID")', function() {
      // uncomment below and update the code to test the property flagID
      //var instance = new Jsflagr.EvalContext();
      //expect(instance).to.be();
    });

    it('should have the property flagKey (base name: "flagKey")', function() {
      // uncomment below and update the code to test the property flagKey
      //var instance = new Jsflagr.EvalContext();
      //expect(instance).to.be();
    });

  });

}));
