/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Constraint from './model/Constraint';
import CreateConstraintRequest from './model/CreateConstraintRequest';
import CreateFlagRequest from './model/CreateFlagRequest';
import CreateSegmentRequest from './model/CreateSegmentRequest';
import CreateVariantRequest from './model/CreateVariantRequest';
import Distribution from './model/Distribution';
import Error from './model/Error';
import EvalContext from './model/EvalContext';
import EvalDebugLog from './model/EvalDebugLog';
import EvalResult from './model/EvalResult';
import EvaluationBatchRequest from './model/EvaluationBatchRequest';
import EvaluationBatchResponse from './model/EvaluationBatchResponse';
import EvaluationEntity from './model/EvaluationEntity';
import Flag from './model/Flag';
import FlagSnapshot from './model/FlagSnapshot';
import PutDistributionsRequest from './model/PutDistributionsRequest';
import PutFlagRequest from './model/PutFlagRequest';
import PutSegmentReorderRequest from './model/PutSegmentReorderRequest';
import PutSegmentRequest from './model/PutSegmentRequest';
import PutVariantRequest from './model/PutVariantRequest';
import Segment from './model/Segment';
import SegmentDebugLog from './model/SegmentDebugLog';
import SetFlagEnabledRequest from './model/SetFlagEnabledRequest';
import Variant from './model/Variant';
import ConstraintApi from './api/ConstraintApi';
import DistributionApi from './api/DistributionApi';
import EvaluationApi from './api/EvaluationApi';
import FlagApi from './api/FlagApi';
import SegmentApi from './api/SegmentApi';
import VariantApi from './api/VariantApi';


/**
* Flagr_is_a_feature_flagging_AB_testing_and_dynamic_configuration_microservice.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Flagr = require('index'); // See note below*.
* var xxxSvc = new Flagr.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Flagr.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Flagr.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Flagr.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Constraint model constructor.
     * @property {module:model/Constraint}
     */
    Constraint,

    /**
     * The CreateConstraintRequest model constructor.
     * @property {module:model/CreateConstraintRequest}
     */
    CreateConstraintRequest,

    /**
     * The CreateFlagRequest model constructor.
     * @property {module:model/CreateFlagRequest}
     */
    CreateFlagRequest,

    /**
     * The CreateSegmentRequest model constructor.
     * @property {module:model/CreateSegmentRequest}
     */
    CreateSegmentRequest,

    /**
     * The CreateVariantRequest model constructor.
     * @property {module:model/CreateVariantRequest}
     */
    CreateVariantRequest,

    /**
     * The Distribution model constructor.
     * @property {module:model/Distribution}
     */
    Distribution,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The EvalContext model constructor.
     * @property {module:model/EvalContext}
     */
    EvalContext,

    /**
     * The EvalDebugLog model constructor.
     * @property {module:model/EvalDebugLog}
     */
    EvalDebugLog,

    /**
     * The EvalResult model constructor.
     * @property {module:model/EvalResult}
     */
    EvalResult,

    /**
     * The EvaluationBatchRequest model constructor.
     * @property {module:model/EvaluationBatchRequest}
     */
    EvaluationBatchRequest,

    /**
     * The EvaluationBatchResponse model constructor.
     * @property {module:model/EvaluationBatchResponse}
     */
    EvaluationBatchResponse,

    /**
     * The EvaluationEntity model constructor.
     * @property {module:model/EvaluationEntity}
     */
    EvaluationEntity,

    /**
     * The Flag model constructor.
     * @property {module:model/Flag}
     */
    Flag,

    /**
     * The FlagSnapshot model constructor.
     * @property {module:model/FlagSnapshot}
     */
    FlagSnapshot,

    /**
     * The PutDistributionsRequest model constructor.
     * @property {module:model/PutDistributionsRequest}
     */
    PutDistributionsRequest,

    /**
     * The PutFlagRequest model constructor.
     * @property {module:model/PutFlagRequest}
     */
    PutFlagRequest,

    /**
     * The PutSegmentReorderRequest model constructor.
     * @property {module:model/PutSegmentReorderRequest}
     */
    PutSegmentReorderRequest,

    /**
     * The PutSegmentRequest model constructor.
     * @property {module:model/PutSegmentRequest}
     */
    PutSegmentRequest,

    /**
     * The PutVariantRequest model constructor.
     * @property {module:model/PutVariantRequest}
     */
    PutVariantRequest,

    /**
     * The Segment model constructor.
     * @property {module:model/Segment}
     */
    Segment,

    /**
     * The SegmentDebugLog model constructor.
     * @property {module:model/SegmentDebugLog}
     */
    SegmentDebugLog,

    /**
     * The SetFlagEnabledRequest model constructor.
     * @property {module:model/SetFlagEnabledRequest}
     */
    SetFlagEnabledRequest,

    /**
     * The Variant model constructor.
     * @property {module:model/Variant}
     */
    Variant,

    /**
    * The ConstraintApi service constructor.
    * @property {module:api/ConstraintApi}
    */
    ConstraintApi,

    /**
    * The DistributionApi service constructor.
    * @property {module:api/DistributionApi}
    */
    DistributionApi,

    /**
    * The EvaluationApi service constructor.
    * @property {module:api/EvaluationApi}
    */
    EvaluationApi,

    /**
    * The FlagApi service constructor.
    * @property {module:api/FlagApi}
    */
    FlagApi,

    /**
    * The SegmentApi service constructor.
    * @property {module:api/SegmentApi}
    */
    SegmentApi,

    /**
    * The VariantApi service constructor.
    * @property {module:api/VariantApi}
    */
    VariantApi
};
