/*
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 
 *
 * OpenAPI spec version: 1.1.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Jsflagr);
  }
}(this, function(expect, Jsflagr) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Jsflagr.ConstraintApi();
  });

  describe('(package)', function() {
    describe('ConstraintApi', function() {
      describe('createConstraint', function() {
        it('should call createConstraint successfully', function(done) {
          // TODO: uncomment, update parameter values for createConstraint call and complete the assertions
          /*
          var flagID = 789;
          var segmentID = 789;
          var body = new Jsflagr.CreateConstraintRequest();
          body.property = "";
          body.operator = "";
          body.value = "";

          instance.createConstraint(flagID, segmentID, body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Jsflagr.Constraint);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.property).to.be.a('string');
            expect(data.property).to.be("");
            expect(data.operator).to.be.a('string');
            expect(data.operator).to.be("EQ");
            expect(data.value).to.be.a('string');
            expect(data.value).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteConstraint', function() {
        it('should call deleteConstraint successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteConstraint call
          /*
          var flagID = 789;
          var segmentID = 789;
          var constraintID = 789;

          instance.deleteConstraint(flagID, segmentID, constraintID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('findConstraints', function() {
        it('should call findConstraints successfully', function(done) {
          // TODO: uncomment, update parameter values for findConstraints call and complete the assertions
          /*
          var flagID = 789;
          var segmentID = 789;

          instance.findConstraints(flagID, segmentID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Jsflagr.Constraint);
              expect(data.id).to.be.a('number');
              expect(data.id).to.be("0");
              expect(data.property).to.be.a('string');
              expect(data.property).to.be("");
              expect(data.operator).to.be.a('string');
              expect(data.operator).to.be("EQ");
              expect(data.value).to.be.a('string');
              expect(data.value).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putConstraint', function() {
        it('should call putConstraint successfully', function(done) {
          // TODO: uncomment, update parameter values for putConstraint call and complete the assertions
          /*
          var flagID = 789;
          var segmentID = 789;
          var constraintID = 789;
          var body = new Jsflagr.CreateConstraintRequest();
          body.property = "";
          body.operator = "";
          body.value = "";

          instance.putConstraint(flagID, segmentID, constraintID, body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Jsflagr.Constraint);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.property).to.be.a('string');
            expect(data.property).to.be("");
            expect(data.operator).to.be.a('string');
            expect(data.operator).to.be("EQ");
            expect(data.value).to.be.a('string');
            expect(data.value).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
