/*
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 
 *
 * OpenAPI spec version: 1.1.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Jsflagr);
  }
}(this, function(expect, Jsflagr) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Jsflagr.DistributionApi();
  });

  describe('(package)', function() {
    describe('DistributionApi', function() {
      describe('findDistributions', function() {
        it('should call findDistributions successfully', function(done) {
          // TODO: uncomment, update parameter values for findDistributions call and complete the assertions
          /*
          var flagID = 789;
          var segmentID = 789;

          instance.findDistributions(flagID, segmentID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Jsflagr.Distribution);
              expect(data.id).to.be.a('number');
              expect(data.id).to.be("0");
              expect(data.percent).to.be.a('number');
              expect(data.percent).to.be("0");
              expect(data.variantKey).to.be.a('string');
              expect(data.variantKey).to.be("");
              expect(data.variantID).to.be.a('number');
              expect(data.variantID).to.be("0");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('putDistributions', function() {
        it('should call putDistributions successfully', function(done) {
          // TODO: uncomment, update parameter values for putDistributions call and complete the assertions
          /*
          var flagID = 789;
          var segmentID = 789;
          var body = new Jsflagr.PutDistributionsRequest();
          body.distributions = [new Jsflagr.Distribution()];
          body.distributions[0].percent = "0";
          body.distributions[0].variantKey = "";
          body.distributions[0].variantID = "0";

          instance.putDistributions(flagID, segmentID, body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Jsflagr.Distribution);
              expect(data.id).to.be.a('number');
              expect(data.id).to.be("0");
              expect(data.percent).to.be.a('number');
              expect(data.percent).to.be("0");
              expect(data.variantKey).to.be.a('string');
              expect(data.variantKey).to.be("");
              expect(data.variantID).to.be.a('number');
              expect(data.variantID).to.be("0");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
