/*
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 
 *
 * OpenAPI spec version: 1.1.10
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Jsflagr);
  }
}(this, function(expect, Jsflagr) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Jsflagr.TagApi();
  });

  describe('(package)', function() {
    describe('TagApi', function() {
      describe('createTag', function() {
        it('should call createTag successfully', function(done) {
          // TODO: uncomment, update parameter values for createTag call and complete the assertions
          /*
          var flagID = 789;
          var body = new Jsflagr.CreateTagRequest();
          body.value = "";

          instance.createTag(flagID, body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Jsflagr.Tag);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.value).to.be.a('string');
            expect(data.value).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteTag', function() {
        it('should call deleteTag successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteTag call
          /*
          var flagID = 789;
          var tagID = 789;

          instance.deleteTag(flagID, tagID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('findAllTags', function() {
        it('should call findAllTags successfully', function(done) {
          // TODO: uncomment, update parameter values for findAllTags call and complete the assertions
          /*
          var opts = {};
          opts.limit = 789;
          opts.offset = 789;
          opts.valueLike = "valueLike_example";

          instance.findAllTags(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Jsflagr.Tag);
              expect(data.id).to.be.a('number');
              expect(data.id).to.be("0");
              expect(data.value).to.be.a('string');
              expect(data.value).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('findTags', function() {
        it('should call findTags successfully', function(done) {
          // TODO: uncomment, update parameter values for findTags call and complete the assertions
          /*
          var flagID = 789;

          instance.findTags(flagID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Jsflagr.Tag);
              expect(data.id).to.be.a('number');
              expect(data.id).to.be("0");
              expect(data.value).to.be.a('string');
              expect(data.value).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
